version: "3.2"

networks:
  infra:

volumes:
  pg_data:

services:
  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    networks:
      - infra
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
