version: "3.2"

volumes:
  pg_data:

services:
  postgres:
    image: library/postgres:14.5
    restart: 'unless-stopped'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backup:/backup
    secrets:
      - pgsql-pass
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD_FILE: '/run/secrets/pgsql-pass'
      POSTGRES_DB: 'MyDatabase'
      PGDATA: '/var/lib/postgresql/data/pgdata'