version: "3.2"

volumes:
  pg_data:

services:
  postgres:
    image: library/postgres:14.5
    restart: 'unless-stopped'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./backup:/backup
    secrets:
      - pgsql-user
    environment:
      POSTGRES_USER: 'my-postgres-user'
      POSTGRES_PASSWORD_FILE: '/run/secrets/pgsql-user'
      POSTGRES_DB: 'infra'
      PGDATA: '/var/lib/postgresql/data/pgdata'