version: "3.2"

networks:
  infra:
    external: true

volumes:
  pg_data:

secrets:
  pgsql-pass:
    external: true
      
services:
  postgres:
    image: library/postgres:14.5
    restart: 'unless-stopped'
    ports:
      - 5432:5432
    networks:
      - infra
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backup:/backup
    secrets:
      - pgsql-pass
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD_FILE: '/run/secrets/pgsql-pass'
      POSTGRES_DB: 'MyDatabase'
      PGDATA: '/var/lib/postgresql/data/pgdata'
