name: CI

on:
  push:
    branches:
      - "main"
    # paths:
    #   - 'docker-compose.yml'


  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 5 * * *' # At 05:00


jobs:
  deploy:
    name: "Backup database"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/*
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking yes
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          SSH_HOST_KEY: ${{ secrets.DEPLOY_SSH_HOST_KEY }}

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup infra
        run: rsync -azvhP --delete $GITHUB_WORKSPACE prod:/home/github

      - name: Setup secrets
        run: |
          ssh prod 'echo "CF_DNS_API_TOKEN=$(sops -d ./infra/secrets.enc.json |jq -r .cloudflare_token)" > ./infra/.env'
          ssh prod 'echo "PGSQL_PASS=$(sops -d ./infra/secrets.enc.json |jq -r .postgres_pass)" >> ./infra/.env'
          ssh prod 'sops -d ./infra/secrets.enc.json |jq -r .usersfile[0] > ./infra/traefik/usersfile'

      - name: Start infra
        run: ssh prod 'cd infra && sudo docker-compose up -d'

      # - name: Setup backup time
      #   run: ssh prod 'date +"%y-%m-%d_%H:%M" > ./backup/last_backup'

      # - name: Dump old database
      #   env:
      #     PG_USER: ${{ secrets.PG_USER }}
      #   run: ssh prod 'docker-compose exec postgres pg_dumpall -U $PG_USER > /backup/backup_$(cat /backup/last_backup).sql'

      # - name: Stop the container
      #   run: ssh prod 'docker-compose stop postgres'

      # - name: Remove the data volume
      #   run: ssh prod 'docker volume rm pg_data'

      # - name: Start new postgres
      #   run: ssh prod 'docker-compose start postgres'

      # - name: Import the backup
      #   env:
      #     PG_USER: ${{ secrets.PG_USER }}
      #   run: ssh prod 'docker-compose exec postgres sh "psql -U $PG_USER < /backup/backup_$(cat /backup/last_backup).sql"